---
abstract: 'Validate data against a JSON schema'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '1.30'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-Validator
no_index:
  directory:
    - t
    - inc
    - examples
    - t
requires:
  Mojolicious: '7.28'
  perl: '5.010001'
resources:
  IRC: irc://irc.freenode.net/#mojo
  bugtracker: https://github.com/mojolicious/json-validator/issues
  homepage: https://mojolicious.org
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/mojolicious/json-validator.git
version: '3.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
